### PR TITLE
Release v1.3

### PR DESCRIPTION
**Pull request by francisco-dlp**
There is a test release at https://test.pypi.org/project/hyperspy-gui-ipywidgets/1.3.0/

### CODE REVIEW

**Comment by francisco-dlp** [comment]
@ericpre, is this v1.3?

**Comment by ericpre** [comment]
Add python 3.8?

**Comment by francisco-dlp** [comment]
Done

**Comment by ericpre** [comment]
Sorry I was not precise: I was thinking in the classifier of `setup.py`

**Comment by jlaehne** [comment]
@francisco-dlp What is the reason that releases for the gui packages are created only on pypi and not on github? Here the two packages have stalled on v1.1.1

**Pull request merged**
